import { KnowledgeGraphData } from './types';

export const sobkruKnowledgeGraphData: KnowledgeGraphData = {
  nodes: [
    {
      id: 'english',
      label: 'ภาษาอังกฤษ',
      type: 'subject',
      subject: 'english',
      description: 'แผนที่ความรู้วิชาภาษาอังกฤษ',
      size: 42,
      status: 'available',
      progress: 35,
      tags: ['grammar', 'reading', 'conversation'],
    },
    {
      id: 'english-grammar',
      label: 'Grammar',
      type: 'category',
      subject: 'english',
      description: 'หมวดไวยากรณ์ภาษาอังกฤษ',
      size: 32,
      status: 'in_progress',
      progress: 20,
    },
    {
      id: 'parts-of-speech',
      label: 'Parts of Speech',
      type: 'lesson',
      subject: 'english',
      category: 'Grammar',
      description: 'ชนิดของคำในภาษาอังกฤษ',
      size: 24,
      status: 'available',
      lessonSlug: 'parts-of-speech',
      url: '/lessons/parts-of-speech',
    },
    {
      id: 'noun',
      label: 'Noun',
      type: 'topic',
      subject: 'english',
      category: 'Grammar',
      description: 'คำนาม คน สัตว์ สิ่งของ สถานที่ ความคิด',
      size: 16,
      status: 'available',
    },
    {
      id: 'verb',
      label: 'Verb',
      type: 'topic',
      subject: 'english',
      category: 'Grammar',
      description: 'คำกริยา แสดงการกระทำหรือสภาพ',
      size: 16,
      status: 'available',
    },
    {
      id: 'quantifier',
      label: 'Quantifier',
      type: 'lesson',
      subject: 'english',
      category: 'Grammar',
      description: 'คำบอกปริมาณ เช่น much, many, some, any',
      size: 22,
      status: 'recommended',
      lessonSlug: 'quantifier',
      url: '/lessons/quantifier',
    },
    {
      id: 'countable-noun',
      label: 'Countable Noun',
      type: 'topic',
      subject: 'english',
      category: 'Grammar',
      description: 'คำนามนับได้ ใช้กับ many, few, a few',
      size: 15,
      status: 'available',
    },
    {
      id: 'uncountable-noun',
      label: 'Uncountable Noun',
      type: 'topic',
      subject: 'english',
      category: 'Grammar',
      description: 'คำนามนับไม่ได้ ใช้กับ much, little, a little',
      size: 15,
      status: 'available',
    },
    {
      id: 'math',
      label: 'คณิตศาสตร์ ภาค ก',
      type: 'subject',
      subject: 'math',
      description: 'แผนที่ความรู้คณิตศาสตร์สำหรับสอบ ภาค ก',
      size: 42,
      status: 'available',
      progress: 50,
    },
    {
      id: 'sequence',
      label: 'อนุกรม',
      type: 'lesson',
      subject: 'math',
      category: 'คณิตศาสตร์ ภาค ก',
      description: 'หัวข้อออกสอบบ่อย ใช้จับรูปแบบตัวเลข',
      size: 26,
      status: 'recommended',
      lessonSlug: 'sequence',
      url: '/lessons/sequence',
    },
    {
      id: 'sequence-plus',
      label: 'อนุกรมบวก/ลบ',
      type: 'topic',
      subject: 'math',
      description: 'รูปแบบอนุกรมที่เพิ่มหรือลดแบบคงที่',
      size: 16,
      status: 'available',
    },
    {
      id: 'sequence-multiply',
      label: 'อนุกรมคูณ/หาร',
      type: 'topic',
      subject: 'math',
      description: 'รูปแบบอนุกรมที่ใช้การคูณหรือหาร',
      size: 16,
      status: 'available',
    },
    {
      id: 'law-good-official',
      label: 'การเป็นข้าราชการที่ดี',
      type: 'subject',
      subject: 'law',
      description: 'หมวดกฎหมายและจริยธรรมสำหรับสอบครูผู้ช่วย',
      size: 42,
      status: 'available',
      progress: 25,
    },
    {
      id: 'administrative-act',
      label: 'พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน',
      type: 'lesson',
      subject: 'law',
      category: 'การเป็นข้าราชการที่ดี',
      description: 'กฎหมายสำคัญที่ออกสอบบ่อย',
      size: 25,
      status: 'available',
      lessonSlug: 'administrative-act',
      url: '/lessons/administrative-act',
    },
    {
      id: 'good-governance',
      label: 'พ.ร.ฎ. บริหารกิจการบ้านเมืองที่ดี',
      type: 'lesson',
      subject: 'law',
      category: 'การเป็นข้าราชการที่ดี',
      description: 'หลักการบริหารกิจการบ้านเมืองที่ดี',
      size: 25,
      status: 'available',
      lessonSlug: 'good-governance',
      url: '/lessons/good-governance',
    },
  ],
  links: [
    { source: 'english', target: 'english-grammar', relation: 'contains', strength: 5 },
    { source: 'english-grammar', target: 'parts-of-speech', relation: 'contains', strength: 4 },
    { source: 'parts-of-speech', target: 'noun', relation: 'contains', strength: 3 },
    { source: 'parts-of-speech', target: 'verb', relation: 'contains', strength: 3 },
    { source: 'english-grammar', target: 'quantifier', relation: 'contains', strength: 4 },
    { source: 'quantifier', target: 'countable-noun', relation: 'related', strength: 4 },
    { source: 'quantifier', target: 'uncountable-noun', relation: 'related', strength: 4 },
    { source: 'noun', target: 'countable-noun', relation: 'related', strength: 3 },
    { source: 'noun', target: 'uncountable-noun', relation: 'related', strength: 3 },
    { source: 'math', target: 'sequence', relation: 'contains', strength: 5 },
    { source: 'sequence', target: 'sequence-plus', relation: 'contains', strength: 4 },
    { source: 'sequence', target: 'sequence-multiply', relation: 'contains', strength: 4 },
    { source: 'law-good-official', target: 'administrative-act', relation: 'contains', strength: 5 },
    { source: 'law-good-official', target: 'good-governance', relation: 'contains', strength: 5 },
    { source: 'administrative-act', target: 'good-governance', relation: 'related', strength: 2 },
  ],
};
